version: '3.8'

# Project name for better identification
# name: ldap-meli-challenge

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: ldap-meli-challenge-server
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Mercado Libre"
      LDAP_DOMAIN: "meli.com"
      LDAP_BASE_DN: "dc=meli,dc=com"
      LDAP_ADMIN_PASSWORD: "itachi"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - ldap-meli-challenge-data:/var/lib/ldap
      - ldap-meli-challenge-config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    hostname: ldap.meli.com
    command: --copy-service

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: ldap-meli-challenge-admin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

volumes:
  ldap-meli-challenge-data:
    driver: local
  ldap-meli-challenge-config:
    driver: local 